// Loads every asset the game needs, then hands off to the Menu scene.
// Shows a small progress bar.

import { PERSONA_ASSET_KEYS } from "../characters.js";

// Bump this whenever a sprite at an existing filename changes (e.g. we
// regenerate enemy_jargon_blob.png in place). vercel.json USED to mark
// /play/assets/* as Cache-Control: immutable, which trains browsers to
// never revalidate even on hard-refresh — adding ?v=N busts old caches
// because the URL becomes a fresh resource the browser hasn't seen.
const ASSET_VERSION = "14";

// Pose names — every Swiirl skin ships this same 17-frame set, extracted
// by tools/extract-character-sheet.mjs from a 1+8+4+4 grid sheet.
const SWIIRL_FRAMES = [
  "idle",
  "walk_1", "walk_2", "walk_3", "walk_4",
  "run_1", "run_2", "run_3", "run_4",
  "jump", "fall", "skid", "crouch", "collect", "hurt", "celebrate", "bounce",
];

// Available player skins. Each one is a complete 17-frame set in
// play/assets/sprites/ under <skin>_<frame>.png. Add a new id here +
// drop the PNGs in to ship a new variant.
export const SKINS = ["classic", "beanie", "ninja", "rookie", "breeze", "closer", "glitz", "denim", "noir", "cozy", "specs", "navy"];
// The skin whose frames also get loaded under bare keys (idle, walk_1,...)
// so legacy scenes that don't know about skins still render something.
export const DEFAULT_SKIN = "beanie";

const WORLD_IMAGES = [
  "tile_ground", "tile_grass", "tile_platform", "tile_brick", "tile_shaft_wall",
  // L6 rooftop — concrete deck + 8 industrial props for the bonus boss arena.
  "tile_rooftop_concrete",
  "prop_parapet", "prop_hvac", "prop_maintenance_shed", "prop_water_tower",
  "prop_satellite_dish", "prop_antenna_mast", "prop_helipad_h", "prop_vent_stack",
  // Per-level themed obstacles (one signature per level — bulletin board in
  // the park, cubicle wall in the office, velvet rope in the brand HQ,
  // server rack in the data lake, marble pillar at the summit).
  "obstacle_bulletin_board", "obstacle_cubicle_wall", "obstacle_velvet_rope",
  "obstacle_server_rack",    "obstacle_marble_pillar",
  "cloud", "sparkle",
  "enemy_jargon_blob", "enemy_ghost", "enemy_paperwork", "enemy_boss",
  "projectile_paper",
  "insight", "signal_speed", "signal_shield", "signal_growth",
  "brand", "brand_happy",
  "bg_far", "bg_mid", "bg_near", "bg_tower",
  "enemy_deadline_bot",
  "bg_data_lake",
  "bg_executive",
  // Per-level boss sprites. Each BossBase subclass now passes its own
  // texture key in the constructor so we can ship distinct art per fight.
  "enemy_boss_l1", "enemy_boss_l2", "enemy_boss_l3", "enemy_boss_l4", "enemy_boss_l5",
  // VFX flipbooks — one frame per file, animation registered below.
  "vfx_swipe_1", "vfx_swipe_2", "vfx_swipe_3", "vfx_swipe_4",
  "vfx_bolt_1",  "vfx_bolt_2",  "vfx_bolt_3",  "vfx_bolt_4",
  "vfx_pound_1", "vfx_pound_2", "vfx_pound_3", "vfx_pound_4",
  "vfx_bash_1",  "vfx_bash_2",  "vfx_bash_3",  "vfx_bash_4",
  // Persona portraits + attack frames. Generated by tools/generate-personas.mjs.
  ...PERSONA_ASSET_KEYS,
];

export class BootScene extends Phaser.Scene {
  constructor() { super("Boot"); }

  preload() {
    const { width, height } = this.scale;
    const barW = 380;
    const barH = 6;
    const cx = width / 2;
    const cy = height / 2 + 40;

    const fill = this.add.rectangle(cx - barW / 2, cy, 0, barH, 0xb892e0).setOrigin(0, 0.5);
    const track = this.add.rectangle(cx, cy, barW, barH, 0xffffff, 0.12).setOrigin(0.5).setDepth(-1);
    const label = this.add.text(cx, cy - 24, "loading swiirl", {
      fontFamily: "system-ui, -apple-system, sans-serif",
      fontSize: "18px",
      color: "#dcc7f2",
    }).setOrigin(0.5);

    this.load.on("progress", (v) => {
      fill.width = barW * v;
    });
    this.load.on("complete", () => {
      label.setText("ready");
      track.setAlpha(0);
      fill.setAlpha(0);
    });

    // Per-skin frames. Keys are `<skin>_<frame>` (e.g. "classic_idle").
    for (const skin of SKINS) {
      for (const k of SWIIRL_FRAMES) {
        this.load.image(`${skin}_${k}`, `assets/sprites/${skin}_${k}.png?v=${ASSET_VERSION}`);
      }
    }
    // Bare keys (idle, walk_1, …) point at the default skin so any legacy
    // code that references unprefixed frames still works without a rewrite.
    for (const k of SWIIRL_FRAMES) {
      this.load.image(k, `assets/sprites/${DEFAULT_SKIN}_${k}.png?v=${ASSET_VERSION}`);
    }
    // World assets.
    for (const k of WORLD_IMAGES) {
      this.load.image(k, `assets/world/${k}.png?v=${ASSET_VERSION}`);
    }
  }

  create() {
    this.registerAnimations();
    this.scene.start("Menu");
  }

  registerAnimations() {
    const a = this.anims;

    // One walk + run animation per skin, plus bare-key versions tied to
    // the default skin for legacy callers.
    const registerWalk = (key, prefix) => {
      if (a.exists(key)) return;
      a.create({
        key,
        frames: [1, 2, 3, 4].map(n => ({ key: `${prefix}walk_${n}` })),
        frameRate: 9, repeat: -1,
      });
    };
    const registerRun = (key, prefix) => {
      if (a.exists(key)) return;
      a.create({
        key,
        frames: [1, 2, 3, 4].map(n => ({ key: `${prefix}run_${n}` })),
        frameRate: 13, repeat: -1,
      });
    };

    for (const skin of SKINS) {
      registerWalk(`${skin}_walk`, `${skin}_`);
      registerRun(`${skin}_run`,   `${skin}_`);
    }
    registerWalk("walk", "");
    registerRun("run", "");

    // VFX flipbook — 4 frames at 18fps = ~220ms total, matches the old
    // slashArc tween window so combat timing stays the same.
    if (!a.exists("vfx_swipe_anim")) {
      a.create({
        key: "vfx_swipe_anim",
        frames: [1, 2, 3, 4].map(n => ({ key: `vfx_swipe_${n}` })),
        frameRate: 18, repeat: 0,
      });
    }
    // Bolt loops while the projectile is in flight (repeat:-1).
    if (!a.exists("vfx_bolt_anim")) {
      a.create({
        key: "vfx_bolt_anim",
        frames: [1, 2, 3, 4].map(n => ({ key: `vfx_bolt_${n}` })),
        frameRate: 16, repeat: -1,
      });
    }
    // Pound + bash play once on cue.
    if (!a.exists("vfx_pound_anim")) {
      a.create({
        key: "vfx_pound_anim",
        frames: [1, 2, 3, 4].map(n => ({ key: `vfx_pound_${n}` })),
        frameRate: 14, repeat: 0,
      });
    }
    if (!a.exists("vfx_bash_anim")) {
      a.create({
        key: "vfx_bash_anim",
        frames: [1, 2, 3, 4].map(n => ({ key: `vfx_bash_${n}` })),
        frameRate: 14, repeat: 0,
      });
    }
  }
}
